Repository Team-SPREAD/Puzzle-FE, pull requests merged in 2024-11, with the labels that each got.

#74 [#73]chore: build.sh 추가
  build.sh
Labels: low

#76 Feat/#75/help
  src/components/Canvas/Canvas.tsx
  src/components/Layout/Modal/GuildModal/index.tsx
  src/components/Layout/ProcessNav/Index.tsx
  src/components/ReactFlowCanvas/InputForNode.tsx
  src/components/StageGimmicks/DiscussionBoxTemplate.tsx
  src/components/StageGimmicks/PersonaBoxTemplate.tsx
  src/components/StageGimmicks/ProblemSolvingBoxTemplate.tsx
  src/components/StageGimmicks/SpreadBoxTemplate.tsx
  src/components/StageGimmicks/StageGimmicks.tsx
  src/components/StageGimmicks/TopicVoteTemplate.tsx
  src/components/StageGimmicks/UserStoryTemplate.tsx
  src/components/StageGimmicks/VisionBoxTemplate.tsx
  src/store/useModalStore.ts
Labels: low

#78 [#71] Feat : 단계 완료 시 캡쳐 로직 구현
  src/app/api/canvas-axios.ts
  src/app/dashboard/page.tsx
  src/components/Canvas/Canvas.tsx
  src/components/DashBoard/BoardCard.tsx
  src/components/Layout/Vote/index.tsx
  src/hooks/vote/useVoteProgress.ts
  src/store/vote/processStore.ts
Labels: maru

#79 [#77]Refactor: 2단계 UI/UX 수정 및 투표 인원 수 개선
  src/components/Layout/Vote/Modal/VotingModal.tsx
  src/components/Layout/Vote/index.tsx
  src/components/Vision.tsx
  src/hooks/vote/useVoteProgress.ts
  src/lib/types.ts
Labels: bug, low

#81 [#80]Feat: live curosr UserName으로 변경
  package-lock.json
  package.json
  src/app/api/liveblocks-auth/route.ts
  src/components/Room.tsx
  src/liveblocks.config.ts
Labels: low

#82 [#71] Feat: 마무리 단계에서 단계 결과 조회
  package-lock.json
  package.json
  src/app/api/canvas-axios.ts
  src/components/Canvas/Canvas.tsx
  src/components/DashBoard/BoardOverview.tsx
  src/components/Layout/Vote/Modal/VotingModal.tsx
  src/components/MarkdownEditor.tsx
  src/components/ReactFlowCanvas/index.tsx
  src/components/Templates/Result.tsx
  src/liveblocks.config.ts
  src/styles/markdown.css
Labels: maru

#84 [#83] 10단계 마크다운 복사 로직 구현
  package-lock.json
  package.json
  src/components/MarkdownEditor.tsx
  src/components/Templates/Result.tsx
Labels: maru

#87 [#86]Fix: 대시보드 팀 보드가 안 불러오지는 오류 수정
  src/app/dashboard/[userId]/page.tsx
  src/components/DashBoard/BoardGrid.tsx
Labels: bug, low

#88 [#72] Refactor: RightNav UI/UX 개선
  public/images/headPhone.svg
  public/images/microphone.svg
  public/images/phone-slash.svg
  public/images/phone.svg
  public/images/play.svg
  public/images/play_red.svg
  public/images/stop.svg
  public/images/stop_red.svg
  src/app/dashboard/[userId]/page.tsx
  src/app/globals.css
  src/components/Canvas/Canvas.tsx
  src/components/DashBoard/Header.tsx
  src/components/DashBoard/SideBar.tsx
  src/components/Layout/RightNav/AudioPlayer.tsx
  src/components/Layout/RightNav/GroupCall/GroupCallController.tsx
  src/components/Layout/RightNav/GroupCall/index.tsx
  src/components/Layout/RightNav/LiveAvatars/Avater.tsx
  src/components/Layout/RightNav/LiveAvatars/index.tsx
  src/components/Layout/RightNav/SoundBlocks/SoundBlock.tsx
  src/components/Layout/RightNav/SoundBlocks/index.tsx
  src/components/Layout/RightNav/SoundBox.tsx
  src/components/Layout/RightNav/Timer.tsx
  src/components/Layout/RightNav/index.tsx
  src/hooks/useSendBirdCalls.ts
  src/lib/sound-data.ts
  src/liveblocks.config.ts
  src/utils/getContrastingColor.ts
  tailwind.config.ts
Labels: maru

#91 [#89]Refactor: canvas 오류 수정 및 개선
  src/app/api/dashboard-axios.ts
  src/components/Layout/Modal/GuildModal/index.tsx
  src/components/Layout/ProcessNav/Index.tsx
  src/components/Persona.tsx
  src/components/Room.tsx
  src/components/Spread.tsx
  src/components/StageGimmicks/ProblemSolvingBoxTemplate.tsx
  src/components/StageGimmicks/UserStoryTemplate.tsx
  src/components/StageGimmicks/VisionBoxTemplate.tsx
  src/components/Story.tsx
  src/components/Vision.tsx
  src/hooks/vote/useProcessProgress.ts
  src/hooks/vote/useVoteProgress.ts
  src/lib/types.ts
  src/store/vote/processStore.ts
Labels: low

#93 [#92]feat: 단계 위치 실시간 공유
  src/components/Layout/ProcessNav/ProcessBar.tsx
Labels: low

#95 [#72] Refactor: RightNav 사이즈 수정
  src/app/page.tsx
  src/components/Layout/RightNav/AudioPlayer.tsx
  src/components/Layout/RightNav/GroupCall/GroupCallController.tsx
  src/components/Layout/RightNav/GroupCall/LiveCallUser.tsx
  src/components/Layout/RightNav/GroupCall/LiveCallUsers.tsx
  src/components/Layout/RightNav/GroupCall/index.tsx
  src/components/Layout/RightNav/LiveAvatars/Avater.tsx
  src/components/Layout/RightNav/LiveAvatars/index.tsx
  src/components/Layout/RightNav/SoundBlocks/SoundBlock.tsx
  src/components/Layout/RightNav/Timer.tsx
  src/components/Layout/RightNav/index.tsx
  src/lib/sound-data.ts
Labels: maru

#97 [#94]faet & refactor : Pricing Page추가 및 전체적인 문구 , UI 수정
  src/app/dashboard/[userId]/page.tsx
  src/app/page.tsx
  src/components/DashBoard/Pricing.tsx
  src/components/DashBoard/SideBar.tsx
  src/components/Discussion.tsx
  src/components/Persona.tsx
  src/components/StageGimmicks/DiscussionBoxTemplate.tsx
  src/components/StageGimmicks/PersonaBoxTemplate.tsx
  src/components/StageGimmicks/ProblemSolvingBoxTemplate.tsx
  src/components/StageGimmicks/TopicVoteTemplate.tsx
  src/components/StageGimmicks/VisionBoxTemplate.tsx
  src/components/Templates/Discussion.tsx
  src/components/Templates/IceBreaking.tsx
  src/components/Templates/Persona.tsx
  src/components/Templates/ProblemSolving.tsx
  src/components/Templates/Result.tsx
  src/components/Templates/RoleAssignment.tsx
  src/components/Templates/SpreadIdeas.tsx
  src/components/Templates/TopicSelection.tsx
  src/components/Templates/UserStory.tsx
  src/components/Templates/VisionFinding.tsx
Labels: low

#98 [#96] Feat: 10단계 디테일 추가
  public/images/logo/Figma.png
  public/images/logo/Notion.png
  public/lotties/confetti.json
  public/lotties/puzzle.json
  src/components/AniModals/MarkDownModal.tsx
  src/components/AniModals/ResultModal.tsx
  src/components/Canvas/Canvas.tsx
  src/components/StageGimmicks/StageGimmicks.tsx
  src/components/StageGimmicks/configs.ts
  src/components/StageGimmicks/types.ts
  src/components/Templates/Result.tsx
  src/store/useMarkdownStore.ts
Labels: maru

#99 [#72] Style: RightNav 위치 조정
  src/components/Layout/RightNav/index.tsx
Labels: maru

#101 [#100/]Refactor: currentStep 호출 방식 개선
  src/app/api/dashboard-axios.ts
  src/components/Room.tsx
Labels: low

#103 [#102] API 호출 시 ProgressModal 표시 추가
  src/app/404/page.tsx
  src/app/api/dashboard-axios.ts
  src/app/page.tsx
  src/components/AniModals/ProgressModal.tsx
  src/components/AniModals/ResultModal.tsx
  src/components/Canvas/Canvas.tsx
  src/hooks/vote/useProcessProgress.ts
  src/hooks/vote/useVoteProgress.ts
  src/store/useProgressModalStore.ts
Labels: maru

#105 [#104] Feat : roomToken 유효 검사 로직 추가
  src/app/board/[boardId]/page.tsx
  src/components/Canvas/Canvas.tsx
  src/components/DashBoard/BoardCard.tsx
  src/components/DashBoard/Header.tsx
  src/components/DashBoard/SideBar.tsx
  src/components/DashBoard/TeamMembersBar.tsx
  src/components/Layout/RightNav/AudioPlayer.tsx
  src/components/Layout/RightNav/LiveAvatars/index.tsx
  src/components/Layout/RightNav/Timer.tsx
  src/components/Room.tsx
  src/hooks/vote/useProcessProgress.ts
  src/hooks/vote/useVoteProgress.ts
  src/store/vote/processStore.ts
Labels: maru

#106 [#10] Refactor: 토큰 없을 경우 루트 경로로 이동
  src/app/dashboard/[userId]/page.tsx
Labels: maru
